.TH gen-bug-report "1" "January 2009"
.SH NAME
gen-bug-report \- Generate a bug report for TsumuFS.
.SH SYNOPSIS
.B gen-bug-report
.SH DESCRIPTION
.TP
\fBgen-bug-report91)\fR is a helpful addition to the \fBtsumufs(1)\fR
suite of tools that gathers system information to assist in bug
reporting.
.SH AUTHOR
Google, Inc.
