.TH is-connected "1" "January 2009"
.SH NAME
is-connected \- Check if TsumuFS is connected to the fileserver.
.SH SYNOPSIS
.B is-connected
.SH DESCRIPTION
.TP
\fBis-connected(1)\fR is a shortcut script to determine if a
\fBtsumufs(1)\fR mount is connected to it's backend server.
.SH AUTHOR
Google, Inc.
