.TH is-dirty "1" "January 2009"
.SH NAME
is-dirty \- Check to see if a file changed since it was last cached.
.SH SYNOPSIS
.B is-dirty [\fIfilename\fR]
.SH DESCRIPTION
.TP
\fBis-dirty(1)\fR is a shortcut script to determine if a file has
changed since it was last cached to disk.
.SH AUTHOR
Google, Inc.
