#!/bin/bash

fusermount -u test

PID=$(ps ax |grep tsumufs |grep -v grep |awk '{ print $1 }')
if [ "$PID" != "" ] && [ "$1" == "kill" ]; then
	sleep 5

	PID=$(ps ax |grep tsumufs |grep -v grep |awk '{ print $1 }')
	if [ "$PID" != "" ] && [ "$1" == "kill" ]; then
		kill -KILL $PID
	fi
fi
