#!/usr/bin/python2.4
# -*- python -*-
#
# Copyright (C) 2008  Google, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
TsumuFS, a NFS-based caching filesystem.

This file contains the startup code that launches into the FuseThread
class. See that module for more details.
"""

import os
import sys

mode = "development"

if mode == "development":
  # Try to find our file
  try:
    path = os.readlink(__file__)
  except OSError:
    path = __file__
    
  path = path.split("/")          # Split the path up into an array
  path = path[0:-2]               # Remove the last two elements
  path = "/".join(path) + "/lib"  # rejoin and add /lib
  sys.path.append(path)

import tsumufs

if __name__ == '__main__':
  # Fork so we don't have to wait on the client side.
  #
  # NB: fuselib should do this for us already, but for some reason in
  #     python it doesn't happen.
  
  try:
    pid = os.fork()
  except OSError:
    sys.stderr.write("Unable to fork.\n")
    sys.exit(1)
    
  if pid != 0:
    sys.exit(0)
    
  server = tsumufs.FuseThread()
  server.multithreaded = 1
  server.main()
  server.shutdown()
