#!/usr/bin/python2.4
# -*- python -*-
#
# Copyright (C) 2008  Google, Inc. All Rights Reserved.
# Copyright (C) 2012  Michael Bryant.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

'''
TsumuFS, an overlay caching filesystem.

This file contains the startup code that launches the fuse filesystem via
the TsumuFS Operations subclass.
'''

import fuse
import tsumufs
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('basedir')
parser.add_argument('mountpoint')
parser.add_argument('--cachedir', default=None)
parser.add_argument('--specfile', default=os.path.expanduser('~/.tsumufsrc'))
parser.add_argument('-f', '--foreground', default=False)
parser.add_argument('-d', '--debug', default=False)
parser.add_argument('-s', '--nothreads', default=False)

def main():
    args = parser.parse_args()
    args.mountpoint = args.mountpoint.rstrip('/')
    args.basedir = args.basedir.rstrip('/')
    if not args.cachedir:
        args.cachedir = '/var/cache/tsumufs/%s-%s' % (args.basedir.replace('/', '-'), args.mountpoint.replace('/', '-')
    fusefs = fuse.FUSE(
        tsumufs.TsumuFS(basedir=args.basedir, cachedir=args.cachedir, specfile=args.specfile),
        args.mountpoint,
        foreground = args.foreground,
        debug = args.debug,
        nothreads = args.nothreads,
    )

if __name__ == '__main__':
    main()
